import { db } from "./db";
import { companies } from "./schema";
import { eq } from "drizzle-orm";

interface SeedCompany {
  name: string;
  website: string;
  atsType: string;
  atsUrl: string;
  sector: string;
  priority: number;
  country: string;
  indiaExpansion: boolean;
  remoteFriendly: boolean;
  companySize: string;
  fundingStage: string;
  lastFundingDate: string;
}

const SEED_COMPANIES: SeedCompany[] = [
  // Global Product / AI / DevTools
  {
    name: "Stripe",
    website: "https://stripe.com/jobs",
    atsType: "greenhouse",
    atsUrl: "stripe",
    sector: "FinTech",
    priority: 10,
    country: "USA",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "5000+",
    fundingStage: "Series H",
    lastFundingDate: "2023-03-15",
  },
  {
    name: "Notion",
    website: "https://notion.so/careers",
    atsType: "lever",
    atsUrl: "notion",
    sector: "Productivity Tools",
    priority: 9,
    country: "USA",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "500-1000",
    fundingStage: "Series C",
    lastFundingDate: "2021-10-08",
  },
  {
    name: "Linear",
    website: "https://linear.app/careers",
    atsType: "ashby",
    atsUrl: "linear",
    sector: "Productivity Tools",
    priority: 10,
    country: "USA",
    indiaExpansion: false,
    remoteFriendly: true,
    companySize: "50-100",
    fundingStage: "Series A",
    lastFundingDate: "2020-11-12",
  },
  {
    name: "Vercel",
    website: "https://vercel.com/careers",
    atsType: "greenhouse",
    atsUrl: "vercel",
    sector: "DevTools",
    priority: 10,
    country: "USA",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "500-1000",
    fundingStage: "Series D",
    lastFundingDate: "2021-11-23",
  },
  {
    name: "Figma",
    website: "https://figma.com/careers",
    atsType: "greenhouse",
    atsUrl: "figma",
    sector: "Design",
    priority: 10,
    country: "USA",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "1000-5000",
    fundingStage: "Acquisition",
    lastFundingDate: "2022-09-15",
  },
  {
    name: "Postman",
    website: "https://postman.com/careers",
    atsType: "greenhouse",
    atsUrl: "postman",
    sector: "DevTools",
    priority: 9,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "1000-5000",
    fundingStage: "Series D",
    lastFundingDate: "2021-08-18",
  },
  {
    name: "Sentry",
    website: "https://sentry.io/careers",
    atsType: "greenhouse",
    atsUrl: "sentry",
    sector: "DevTools",
    priority: 9,
    country: "USA",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "500-1000",
    fundingStage: "Series E",
    lastFundingDate: "2022-05-24",
  },
  {
    name: "PostHog",
    website: "https://posthog.com/careers",
    atsType: "ashby",
    atsUrl: "posthog",
    sector: "DevTools",
    priority: 9,
    country: "USA",
    indiaExpansion: false,
    remoteFriendly: true,
    companySize: "50-100",
    fundingStage: "Series A",
    lastFundingDate: "2020-03-24",
  },
  // Indian Startups Watchlist
  {
    name: "Razorpay",
    website: "https://razorpay.com/careers",
    atsType: "greenhouse",
    atsUrl: "razorpay",
    sector: "FinTech",
    priority: 10,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "1000-5000",
    fundingStage: "Series F",
    lastFundingDate: "2021-12-10",
  },
  {
    name: "CRED",
    website: "https://cred.club/careers",
    atsType: "lever",
    atsUrl: "cred",
    sector: "FinTech",
    priority: 9,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "1000-5000",
    fundingStage: "Series F",
    lastFundingDate: "2022-06-09",
  },
  {
    name: "Groww",
    website: "https://groww.in/careers",
    atsType: "greenhouse",
    atsUrl: "groww",
    sector: "FinTech",
    priority: 8,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "1000-5000",
    fundingStage: "Series E",
    lastFundingDate: "2021-10-25",
  },
  {
    name: "Zepto",
    website: "https://zepto.com/careers",
    atsType: "greenhouse",
    atsUrl: "zepto",
    sector: "E-commerce",
    priority: 8,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "1000-5000",
    fundingStage: "Series F",
    lastFundingDate: "2024-06-21",
  },
  {
    name: "Rocketlane",
    website: "https://rocketlane.com/careers",
    atsType: "greenhouse",
    atsUrl: "rocketlane",
    sector: "B2B SaaS",
    priority: 9,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "50-200",
    fundingStage: "Series B",
    lastFundingDate: "2024-05-30",
  },
  {
    name: "Ultrahuman",
    website: "https://ultrahuman.com/careers",
    atsType: "ashby",
    atsUrl: "ultrahuman",
    sector: "HealthTech",
    priority: 9,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "50-200",
    fundingStage: "Series B",
    lastFundingDate: "2024-03-20",
  },
  {
    name: "Sarvam AI",
    website: "https://sarvam.ai/careers",
    atsType: "custom",
    atsUrl: "https://sarvam.ai",
    sector: "AI",
    priority: 10,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "5-50",
    fundingStage: "Series A",
    lastFundingDate: "2023-12-07",
  },
  {
    name: "Krutrim",
    website: "https://krutrim.com/careers",
    atsType: "custom",
    atsUrl: "https://krutrim.com",
    sector: "AI",
    priority: 9,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "50-200",
    fundingStage: "Series A",
    lastFundingDate: "2024-01-26",
  },
  {
    name: "Pixxel",
    website: "https://pixxel.space/careers",
    atsType: "lever",
    atsUrl: "pixxel",
    sector: "Robotics",
    priority: 8,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "50-200",
    fundingStage: "Series B",
    lastFundingDate: "2023-06-01",
  },
  {
    name: "Sprinto",
    website: "https://sprinto.com/careers",
    atsType: "lever",
    atsUrl: "sprinto",
    sector: "Cybersecurity",
    priority: 9,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "50-200",
    fundingStage: "Series B",
    lastFundingDate: "2024-04-10",
  },
  {
    name: "DevRev",
    website: "https://devrev.ai/careers",
    atsType: "greenhouse",
    atsUrl: "devrev",
    sector: "B2B SaaS",
    priority: 9,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "200-500",
    fundingStage: "Series A",
    lastFundingDate: "2024-08-15",
  },
  {
    name: "Juspay",
    website: "https://juspay.in/careers",
    atsType: "custom",
    atsUrl: "https://juspay.in",
    sector: "FinTech",
    priority: 8,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: false,
    companySize: "500-1000",
    fundingStage: "Series C",
    lastFundingDate: "2021-12-16",
  },
  {
    name: "Atomicwork",
    website: "https://atomicwork.com/careers",
    atsType: "ashby",
    atsUrl: "atomicwork",
    sector: "Productivity Tools",
    priority: 8,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "50-200",
    fundingStage: "Seed",
    lastFundingDate: "2023-09-20",
  },
  {
    name: "Wingify",
    website: "https://wingify.com/careers",
    atsType: "lever",
    atsUrl: "wingify",
    sector: "Productivity Tools",
    priority: 8,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "200-500",
    fundingStage: "Bootstrapped",
    lastFundingDate: "N/A",
  },
  {
    name: "Ongraph",
    website: "https://www.ongraph.com/careers",
    atsType: "custom",
    atsUrl: "https://www.ongraph.com/careers",
    sector: "DevTools",
    priority: 7,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "200-500",
    fundingStage: "Bootstrapped",
    lastFundingDate: "N/A",
  },
  {
    name: "TechAhead",
    website: "https://www.techaheadcorp.com/careers/",
    atsType: "custom",
    atsUrl: "https://www.techaheadcorp.com/careers/",
    sector: "Product Companies",
    priority: 7,
    country: "India",
    indiaExpansion: true,
    remoteFriendly: true,
    companySize: "200-500",
    fundingStage: "Bootstrapped",
    lastFundingDate: "N/A",
  },
];

export async function runSeed() {
  console.log(`[Seed] Starting database seeding of ${SEED_COMPANIES.length} target companies...`);
  
  let inserted = 0;
  let skipped = 0;

  for (const c of SEED_COMPANIES) {
    const existing = await db.query.companies.findFirst({
      where: eq(companies.name, c.name),
    });

    if (!existing) {
      await db.insert(companies).values({
        name: c.name,
        website: c.website,
        atsType: c.atsType,
        atsUrl: c.atsUrl,
        sector: c.sector,
        priority: c.priority,
        country: c.country,
        indiaExpansion: c.indiaExpansion,
        remoteFriendly: c.remoteFriendly,
        companySize: c.companySize,
        fundingStage: c.fundingStage,
        lastFundingDate: c.lastFundingDate,
        hiringMomentum: 50,
        healthScore: 60,
        isMonitored: true,
      });
      inserted++;
    } else {
      skipped++;
    }
  }

  console.log(`[Seed] Seeding completed. Registered ${inserted} new companies. (Skipped ${skipped} duplicates).`);
}
